wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691314297.978372
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      - 103
      2:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      - 103
      3:
      - 7
      - 13
      - 23
      - 24
      4: 3.8.5
      5: 0.15.8
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: images._type
      5: 1
      6:
      - 1
    - 1: images.width
      5: 1
      6:
      - 1
    - 1: images.height
      5: 1
      6:
      - 1
    - 1: images.format
      5: 1
      6:
      - 1
    - 1: images.count
      5: 1
      6:
      - 1
    - 1: images.filenames
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
