wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691365834.709786
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      - 103
      2:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 63
      - 103
      3:
      - 13
      - 23
      4: 3.8.5
      5: 0.15.8
      8:
      - 5
